### ISSUE TITLE
First contribution

### ISSUE THREAD

**Issue by ayush-kl** [AtriChatterjee1/Heart--Disease#5]
Hi

**Comment by AtriChatterjee1** [comment]
Hi! Thanks for submitting your first Issue

**Comment by ayush-kl** [comment]
Can i get some work in your repo?

**Comment by AtriChatterjee1** [comment]
@ayush-kl Yeah, the readme is kind of incomplete, you can complete that . Further, you can also work in improving the model's accuracy
